### PR TITLE
[Merge ready] Aggregated => travis ccache, base64 encoding, null separated script, fix LC_ALL, force shellcheck resolve.

### PR DESCRIPTION
**Pull request by bartoszek**
- [x] add `makepkg.conf`
  - [x] add `MAKEFLAGS=-j2`
  - [x] add `COMPRESSXZ=(xz -T 2)`
  - [x] ~test if  `options+=(ccache) in `makepkg.conf` overrides default `options`~
- [x] install ccache in container
  - ~make `arch-travis.sh` add `ccache` to package list if `cache:ccache=true`~
  - [x] ~use `$TRAVIS_HOME/.ccache` to make use of travis `cache:ccache=true`~
  - [x] make ccache configuration persistent across updates. 
  - ~add `ccache_` config vars to `.travis.yml`~
- [x] add pacman cache
  - [x] ~add `casher add` invocation in `arch-travis.sh` on `cache:pacman=true`~
  - [x] move pacman cache to `$TRAVIS_HOME`
  - [x] clean old version of packages from `pacman pkg cache`
- [x] add `eval` ~and `realpath`~ to `arch.mount`
  - [x] use ruby `File.expand_path()` instead of `realpath` (missing from travis image)
refers #55

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Thanks for the PR. I understand that it's still Work In Progress? :)

**Comment by bartoszek** [comment]
Yep :construction:

**Comment by bartoszek** [comment]
This is the minimum range of changes required to leverage Travis caching infrastructure. Rest can be implemented, for specific use case, in `.travis.yml`: [example: AUR-luxcorerender-git](https://github.com/bartoszek/AUR-luxcorerender-git/blob/master/.travis.yml)
### Implementation scope
1. Required
  1.1 `arch:before_install` (init.sh, arch-travis.sh)
  _required to perform system configuration before `pacman` executes_
2. Supplementary 
  2.1  `arch:mount` (arch-travis.sh)
  _allows to cache folders outside of `TRAVIS_BUILD_DIR`_

**Comment by mikkeloscar** [comment]
Thanks a lot!

Would you mind running `shellcheck` on the scripts and fix issues? (I should make this part of the build, to check it on PRs)

I.e.:
```
shellcheck arch-travis.sh 

In arch-travis.sh line 37:
    [[ -z "${volumes[@]}" ]] && return 1
          ^-------------^ SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).


In arch-travis.sh line 39:
    volumes=($(eval echo ${volumes[@]}))
             ^------------------------^ SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
                         ^-----------^ SC2068: Double quote array expansions to avoid re-splitting elements.


In arch-travis.sh line 41:
    volumes=($(ruby -e "ARGV.each{|vol| puts vol.split(':').map{|path| File.expand_path(path)}.join(':')}" "${volumes[@]}"))
             ^-- SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).


In arch-travis.sh line 42:
    echo "Docker volumes: ${volumes[@]}" >&2
                          ^-----------^ SC2145: Argument mixes string and array. Use * or separate argument.


In arch-travis.sh line 43:
    printf " -v %s" ${volumes[*]}
                    ^-----------^ SC2086: Double quote to prevent globbing and word splitting.


In arch-travis.sh line 58:
    ${CONFIG_VOLUMES} \
    ^---------------^ SC2086: Double quote to prevent globbing and word splitting.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
  https://www.shellcheck.net/wiki/SC2145 -- Argument mixes string and array. ...
  https://www.shellcheck.net/wiki/SC2199 -- Arrays implicitly concatenate in ...
```

**Comment by bartoszek** [comment]
Shellcheck is misreporting some intended behaviour as warnings:
```sh
In arch-travis.sh line 58:
    ${CONFIG_VOLUMES} \
    ^---------------^ SC2086: Double quote to prevent globbing and word splitting.
```
Word splitting is the expected behaviour: expanding `docker ${CONFIG_VOLUMES}` to `docker -v src1:dst1 -v src2:dst2` works thanks to word splitting. The same applies for the rest of quoting warnings.

_This results in a path containing separators (space and/or tab) getting broken. Which is a rather rare case at Linux system and could be addressed in README.md._

**Comment by bartoszek** [comment]
Ok, I've made it `shellcheck` compliant, but have to resolve to some ugly hacks to pass `SC2068`  
Merly [this on](https://github.com/bartoszek/arch-travis/blob/3906123bdc2db179a5d477b0d5c72cb6a948c7ce/arch-travis.sh#L56) in `docker` invocation :confused:
Check last paragraph in the [SC2068 wiki](https://github.com/koalaman/shellcheck/wiki/SC2086)

**Comment by mikkeloscar** [comment]
Thanks a lot and sorry for not following up before, I was on vacation for the past weeks.

**Pull request merged**
